### ISSUE TITLE
cppimport for compiling in release mode

### ISSUE THREAD

**Issue by amrit-poudel** [tbenthompson/cppimport#38]
I have recently started using cppimport (a great library, very useful!) along with pybind11. However, I notice that cppimport seems to compile C++ code in debug mode using -g  flag. Also, it does not seem to look for libraries provided in cfg['libraries']. Is there a way to compile in release mode?

<%
cfg['compiler_args'] = ['-std=c++11']
cfg['include_dirs'] = ['/hpc_lib/eigen', '/hpc_lib/pybind11/include',
					   '/hpc_lib/python-3.6.2/include', '/hpc_lib/openblas/include']
cfg['libraries'] = ['/hpc_lib/python-3.6.2/lib',  '/hpc_lib/openblas/lib']
cfg['linker_args'] = ['-lopenblas', '-lgfortran',  '-lpython3.6m']
setup_pybind11(cfg)
%>

I get the following warning and error during link time:

gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/hpc_lib/eigen -I/hpc_lib/pybind11/include -I/hpc_lib/python-3.6.2/include -I/hpc_lib/openblas/include -I/hpc_lib/python-3.6.2/include/python3.6m  -c /src/.rendered.dwf_solver_cpp.cpp -o /tmp/tmpc8iscbum/src/.rendered.dwf_solver_cpp.o -std=c++11 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
warning: no library file corresponding to '/hpc_lib/python-3.6.2/lib' found (skipping)

g++ -pthread -shared -rdynamic /tmp/tmpc8iscbum/src/.rendered.dwf_solver_cpp.o  -lpython3.6m -o /tmp/tmpc8iscbum/dwf_solver_cpp.cpython-36m-x86_64-linux-gnu.so -lopenblas -lgfortran -lpython3.6m
warning: no library file corresponding to '/hpc_lib/openblas/lib' found (skipping)
/binutils/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status

Why does the compiler not pick up the libraries? It seems to pick up fine the header files though.

I have those libraries correctly set in LD_LIBRARY_PATH.

**Comment by tbenthompson** [comment]
It seems like there are a few separate issues here:

* the debug flag `-g` is actually added by the underlying setuptools-based Python extension building code. This is part of `distutils` and it actually uses the same set of flags that Python itself was built with. Unless you're dealing with a strange situation, the added file extension file size resulting from the `-g` flag is going to be negligible. If you really want to, I suspect there's some way we could figure out how to turn that flag off, but it's not simple. 

* The `cfg['libraries']` line is being picked up. You're getting two warnings: 
```
warning: no library file corresponding to '/hpc_lib/python-3.6.2/lib' found (skipping)
warning: no library file corresponding to '/hpc_lib/openblas/lib' found (skipping)
```
I think you want `cfg['library_dirs']` instead? I noticed that this cfg option might not be documented. I'll fix that! 

* The error ` /binutils/bin/ld: cannot find -lopenblas` should be solved by using `cfg['library_dirs']` so that your library directories get picked up. 

* I think you can actually change the `linker_args` line to `cfg['libraries'] = ['openblas', 'gfortran', 'python3.6m']`.

Does that all help?

**Comment by amrit-poudel** [comment]
Thanks for this useful information. I appreciate it. Yes, information on library_dirs was missing which is why I could not figured it out.  I will try this as soon as I have access to work station and report back here. 

In the meantime, is there a way to completely control the compiler args so that compiler does not pick up anything from the Python it was run/built from? I have also noticed that it picks up -L/dirname during link time from Python build as well, even when dirname may have already been deleted. I have only specified -std=c++11 as compiler args, but it picks up -g as well. Code compiled in a debug mode runs about an order of magnitude slower than the one compiled in release mode, especially when external libraries like eigen is used. I definitely do not want to compile with that flag on. 

My only wish is that the compiler would pick stuffs that I specify explicitly, or at least have a way to turn it on/off what it can pick by default from the Python build. That way, cppimport would be equivalent to compiling code from the terminal or using our own makefile, where we control everything and don’t pick stuffs by default except for the ones already provided by the compiler itself.  Do you think something like this is even possible? 

Thanks again for a very nice piece of software!

**Comment by tbenthompson** [comment]
The `-g` flag should have absolutely no effect on performance: https://stackoverflow.com/questions/24117063/is-a-program-compiled-with-g-gcc-flag-slower-than-the-same-program-compiled-wit

Maybe you're getting the `-g` debug symbols flag mixed up with the `-Og` debug optimization level. Unless you're running on some very memory or disk limited hardware like an embedded device, I prefer to include the `-g` flag since it'll make debugging with tools like `gdb` much easier and has no costs except binary size and maybe a tiny hit to the time required to import the library. 

Concerning the addition of unexpected flags, I've thought about this too. While it would be nice to be able to completely control the compilation flags there are a couple reasons, it's not a priority for me at the moment. First, I haven't seen it actually causing any problems -- if those flags are good enough for the Python executable, they're probably good enough for your extension (and that's probably the case for your particular circumstance). In addition, using the same flags that Python was built with avoids a whole range of potential compatibility issues with loading the extension.

That said, if you want to dig in and figure out how to make the change... cppimport actually exports the responsibility for building the extension to distutils/build_ext. You can see and modify the flags used by distutils with 
```
import distutils.sysconfig
# print the default flags
print(distutils.sysconfig.get_config_vars()['PY_CFLAGS'])
# remove the default flags and replace them with just -O3
distutils.sysconfig.get_config_vars()['PY_CFLAGS'] = '-O3'
```
Before adding this complexity to your codebase, I'd suggest profiling to check if the flags are actually affecting performance at all. If not, just use the defaults!

**Comment by amrit-poudel** [comment]
I was able to resolve those errors using library_dirs. However, I still cannot get rid of -g flag, which is compiling code in debug mode instead of in release mode. Debug mode Eigen runs significantly slower than release mode.

**Comment by tbenthompson** [comment]
Did you read my message above on the `-g` flag?

**Comment by amrit-poudel** [comment]
Sorry,  I did not see your message when I posted my question. Thanks a lot for the clarification and the helpful hint. I will try playing around with the distutils to see if I can completely control compiler flags (not that it is important now, because -g and -O3 are used simultaneously so it is probably not affecting the speed of my code, but just for the sake of it). 
Thanks again.

**Comment by amrit-poudel** [comment]
one quick questions. How do I access "cfg" variable from some other python file? Currently, cfg is inside 
<%
cfg[] = []
setup_pybind11(cfg)
%>

Instead of that, I would like to have:
<%
from some_file import some_function
cfg = some_function()
setup_pybind11(cfg)
>%
